version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE=bdocp
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    image: spring-boot-app
    container_name: spring-boot-backend
    depends_on:
      - mysql-db
    ports:
      - "4000:4000"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    image: angular-frontend
    container_name: angular-frontend
    ports:
      - "4200:80"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql-db
    ports:
      - "8082:80"
    networks:
      - app-network
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
